name: CI/CD Pipeline DEV

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: echo "Current NODE_ENV is $NODE_ENV"
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm install
      - run: npm install -g firebase-tools
      - name: Deploy to Firebase DEV
        env:
          NODE_ENV: dev
          FIREBASE_TOKEN: ${{ secrets.FB_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FB_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FB_PRIVATE_KEY }}
        run: npm run deploy