name: CI/CD Pipeline DEV

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: echo "Current NODE_ENV is $NODE_ENV"
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build